# Generated by Django 5.2.6 on 2026-08-18 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz-based recommendation"),
                            ("career_detail", "Per-career detail recommendation"),
                            ("search", "Free-text career search"),
                        ],
                        default="search",
                        max_length=20,
                    ),
                ),
                (
                    "input_hash",
                    models.CharField(
                        db_index=True,
                        help_text="MD5 hash of the canonicalised input — used for deduplication.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Original request payload (query, career data, quiz responses).",
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Structured AI response."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accessed_at", models.DateTimeField(auto_now=True)),
                (
                    "career",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_recommendations",
                        to="core.career",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["recommendation_type", "input_hash"],
                        name="ai_airecomm_recomme_0aaf63_idx",
                    ),
                    models.Index(
                        fields=["career", "recommendation_type"],
                        name="ai_airecomm_career__ad01fa_idx",
                    ),
                ],
            },
        ),
    ]
