# Generated by Django 5.2.6 on 2025-09-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('graduate', 'Graduate'), ('professional', 'Professional')], default='student', max_length=50, null=True),
        ),
    ]
